### PR TITLE
[SCP1]Remove "Software Component" related fields

### PR DESCRIPTION
**Pull request by goreraks**
Initially we decided to keep "Software Component", "Minimum Release" and "Maximum Release" fields that can be maintained for BC Sets. Because of Software Components are being merged, the code split from S/4 and the issues raised while activating a BC Sets in Steampunk environment, we decided not to keep these fields in AFF.

@wurzka had requested to upload a simple example with lesser in file size. So I will create a seperate PR for the same soon.

### CODE REVIEW

**Comment by albertmink** [comment]
This thing with the example is, the example is no longer valid with the changes in the JSON Schema. As a workaround, you could remove the data in the existing example, `softwareComponent`, `minimumRelease` and `maximumRelease`. Or you add the simplified example to this PR.

**Comment by schneidermic0** [comment]
> wurzka had requested to upload a simple example with lesser in file size. So I will create a separate PR for the same soon.

I agree with Albert. We should also update the example so that it is at least is compatible with your changes.

**Comment by schneidermic0** [comment]
Technically, your changes are incompatible. As far as I know SCP1 file format has not been available, yet

**Comment by goreraks** [comment]
Yes, SCP1 file format is not yet available.

**Comment by schneidermic0** [comment]
@goreraks There hasn't been any update to this PR for 6 weeks now. When do you plan to fix the example? Without fixing the example we cannot merge this PR in our main branch because we will see failing tests.

**Comment by schneidermic0** [comment]
No update since more than two months. I have converted this to "draft"

**Pull request closed without merging**
