### PR TITLE
github actions: issue error if mismatch ABAP <> Schema

### PR DESCRIPTION
**Pull request by larshp**
github action will now give an error if the ABAP code and generated schema does not match

Note that "Generate Schemas" is not a required status check, so it will not block merges

ENHO skipped due to https://github.com/SAP/abap-file-formats/issues/409

### CODE REVIEW

**Comment by schneidermic0** [comment]
> github action will now give an error if the ABAP code and generated schema does not mismatch

I guess you mean if they "do not match" or "mismatch", don't you? ;)

**Comment by larshp** [comment]
fixed 😁

**Review by schneidermic0 — COMMENTED** [review]
Cool. 

Looks good to me. 
@SAP/abap-file-formats-team Would someone else review this PR, too?

**Review by wurzka — APPROVED** [review]
LGTM :)

**Review by schneidermic0 — APPROVED** [review]

**Comment by albertmink** [comment]
I like the integration. But maybe we can find a better name of the action?

It took me I while to find the action in this list 
Screenshot 2023-02-02 at 10 13 37

If the main purpose of the action is 'Check if ABAP type and JSON Schema align' then the 'Generate Schemas' is misleading. Actually it generates the JSON Schema but don't provide it as a download or other artefacts, right?

**Comment by schneidermic0** [comment]
> If the main purpose of the action is 'Check if ABAP type and JSON Schema align' then the 'Generate Schemas' is misleading. Actually it generates the JSON Schema but don't provide it as a download or other artefacts, right?

Suggestions: 
- Validate JSON schema against ABAP type
- Validate JSON schema 

More suggestions are welcome :)

**Comment by larshp** [comment]
true, however, on longer term I'd suggest it to actually update the PR with the file

**Comment by jhunni** [comment]
"Validate JSON schema against ABAP type" sounds good to me.
However, the next check in the list is called "Validate JSON".
Maybe rename this one, too, so it's clear what each of them does?

**Comment by schneidermic0** [comment]
> However, the next check in the list is called "Validate JSON"

I had this also in mind, but I think we can differentiate both. 

@larshp **"Executive" Decision:** (as requested by you ;))
Let's keep it short and simple and start with "Validate JSON schema". We can still change it in the future if it is confusing.

**Comment by larshp** [comment]
updated

**Review by schneidermic0 — APPROVED** [review]
Thanks, looks good to me. 👍

**Pull request merged**
