### PR TITLE
Add interface for types used by CLAS & INTF

### PR DESCRIPTION
**Pull request by wurzka**
Interface zif_oo_aff_types_v1 was added

### CODE REVIEW

**Comment by larshp** [comment]
the linter doesnt find the file, need to define a folder structure https://github.com/SAP/abap-file-formats/issues/109

**Comment by wurzka** [comment]
@larshp thank you for your help!

**Comment by wurzka** [comment]
@crasovan and I, we decided to move the types used both by INTF and by CLAS into one common interface.

**Review by schneidermic0 — APPROVED** [review]
Yes, this makes sense to me to introduce reusable types. Maybe we have to change the interface name in the future. See #128.

**Pull request merged**
