### PR TITLE
Validation JSON Schema - JSON Data broken

### LINKED ISSUE #260: Validation JSON Schema - JSON Data broken
Renaming of JSON Schema and the introduction of `formatVersion` broke the validation logic. The JSON schema/instance match is wrong, see line 7
image

We need to load the JSON data and extract the `formatVersion`. Together with the file name we can set up a proper JSON schema/instance match again.

### PR DESCRIPTION
**Pull request by albertmink**
Fixes #260

### CODE REVIEW

**Comment by albertmink** [comment]
The automated JSON validation is now working again.
Sadly, a link inside a Markdown document is broken. The referred url/document has been moved?!

**Comment by schneidermic0** [comment]
I guess the linked document shall point to https://code.visualstudio.com/Docs/languages/json. 

Shall we fix the broken link with this PR or shall we create a dedicated PR?

**Comment by albertmink** [comment]
Just add a commit to this PR ☺️

**Review by schneidermic0 — APPROVED** [review]
LGTM

**Pull request merged**
