### PR TITLE
FUGR: readme add note regarding ABAP pseudo syntax

### PR DESCRIPTION
**Pull request by larshp**
the definition links to https://help.sap.com/doc/abapdocu_cp_index_htm/CLOUD/en-US/index.htm?file=abenabap_functions.htm, which is the ABAP language, but we really want to serialize with the extra ABAP pseudo syntax

always another twist in ABAP 😁 

hmm, the example on help.sap.com shows the commented ABAP pseudo syntax example, which is not what we need, are there any better links?

### CODE REVIEW

**Comment by albertmink** [comment]
better links are welcome!

**Comment by larshp** [comment]
I've added the example directly in the readme, I think its quite important, so its okay to add in the readme?

**Comment by albertmink** [comment]
I think we can put it as-it-is. But isn't it the "same" as the given example.
If this topic function-modules/syntax needs a strict and prominent clarification, then let's do it as in the PR. Otherwise the example could be sufficient.

**Review by albertmink — APPROVED** [review]
Look's good to me.

**Pull request merged**
