### PR TITLE
Align spaces

### LINKED ISSUE #616: Aligning TYPE expressions?
This hurts my eyes,
https://github.com/abapGit/aff_mirror/pull/113/files#diff-a0d5b677bd33100cce15b1ca96c19e9dc1becc29a2103acbfbdf6aa3775f0ae4R5
I dont really mind where its aligned to or unaligned, hurts when its almost aligned

Suggest enabling https://rules.abaplint.org/align_type_expressions/, also note its got a quick fix for the 131 current findings, https://abaplint.app/stats/SAP/abap-file-formats/disabled_rules

### PR DESCRIPTION
**Pull request by albertmink**
fixes #616

AFAIK: This is not a policy that can be achieves by ADT in Eclipse. So there might/will be regressions :unamused:

### CODE REVIEW

**Comment by larshp** [comment]
alternatively we can also do **no** extra spaces before `TYPE` ?

**Review by schneidermic0 — APPROVED** [review]
Thanks, @albertmink.

LGTM

**Review by larshp — APPROVED** [review]

**Comment by albertmink** [comment]
let's not forget to add the actual rule ;)

**Comment by larshp** [comment]
and aligning whitespace 😁

**Pull request merged**
