### PR TITLE
Update zif_aff_types_v1.intf.abap

### PR DESCRIPTION
**Pull request by huber-nicolas**
update zif_aff_types_v1

### CODE REVIEW

**Comment by albertmink** [comment]
Besides the title/description texts, we add ABAP Types.

char[80] needed in https://github.com/SAP/abap-file-formats/pull/662

So we temporarily overrule the abaplint.

**Comment by albertmink** [comment]
@huber-nicolas ready to merge?

**Comment by huber-nicolas** [comment]
> @huber-nicolas ready to merge?

yes you can merge

**Comment by Markus1812** [comment]
What about the exemption for abaplint? We now have a check failure on main (and EDCC) until SUCO is merged.

**Pull request merged**
