### PR TITLE
fix RONT

### PR DESCRIPTION
**Pull request by larshp**
closes https://github.com/SAP/abap-file-formats/issues/434

### CODE REVIEW

**Comment by larshp** [comment]
needs https://github.com/SAP/abap-file-formats/pull/436 to be merged first

**Comment by schneidermic0** [comment]
@Ehret-Thomas Would you check whether the ABAP type in the interface or the schema needs to be adapted/fixed?

**Review by Ehret-Thomas — APPROVED** [review]
Thanks for spotting this mistake in the JSON schema! The maxlength correction for the expanded name looks good to me.

**Review by schneidermic0 — APPROVED** [review]
LGTM

**Pull request merged**
