### PR TITLE
INTF - README.md

### PR DESCRIPTION
**Pull request by larshp**
It takes me multiple tries before I find the files I'm looking for, this adds an overview of all files, which are shown by default via README.md

This moves the overview from `format.md` to `README.md`, readmes are automatically shown for the folder, example: https://github.com/SAP/abap-file-formats/tree/hvam/read2008/file-formats/intf

In the table, there is one line per file, with links, this is especially useful if there are multiple files.

Plus adds a link to the language contained in the file, we'll have at least ABAP + ABAP CDS + DDL + more in the future.

Suggestings for better headings than "Definition" and "Schema" welcome

### CODE REVIEW

**Comment by larshp** [comment]
another thing to add: cardinality

**Comment by huber-nicolas** [comment]
> How about documenting objects that only consists of a JSON file, e.g. `CHKO`?
> 
> Maybe we can separate the README into **Definition** and **Example**. This should be a valid categorization for all objects and makes the definition more prominent.
> 
> # INTF File Format
> ## Definitions
> ABAP Type	JSON Schema	ABAP Documentation
> [`zif_aff_intf_v1.intf.abap`](./type/zif_aff_intf_v1.intf.abap)	[`intf.json`](./intf.json)	[Interface](https://help.sap.com/doc/abapdocu_cp_index_htm/CLOUD/en-US/index.htm?file=abapinterface_definition.htm)
> ## Examples
> File	Content/Description
> [`zif_aff_example.intf.json`](./examples/zif_aff_example.intf.json)	Metadata and descriptions
> [`zif_aff_example.intf.abap`](./examples/zif_aff_example.intf.abap)	ABAP source code
> ## Further Reading
> Documentation of interfaces is not covered, yet.

I like it

**Comment by larshp** [comment]
If going for few files, it would not be an issue, but SAP seems to move in the direction of having more files

So, first think I'd be looking for is an overview of which files are expected for an object type, and after that dive down into one of the files either definition and/or example

**Comment by larshp** [comment]
CHKO, one file equals one line, example(with broken links)

# CHKO File Format

File | Cardinality | Definition | Schema | Example
:--- | :---  | :--- | :--- | :---
`<name>.chko.json` | 1 | [`zif_aff_intf_v1.chko.abap`](./type/zif_aff_intf_v1.chko.abap) | [`chko.json`](./chko.json) | [`foobar.chko.json`](./examples/foobar.chko.json)

**Comment by albertmink** [comment]
I agree on the importance of linkage between file-definition/content. It is also nice as you mentioned, to get an rough idea of how many files are involved. So I am fine with your suggestion.

As long as there is one file, the titles `Definition` and `Schema` are great. So we could start with it.

**Comment by albertmink** [comment]
I wonder how the first column would look like for objects like `FUGR`.

**Comment by larshp** [comment]
FUGR: 😁 yea, me too

perhaps we should try making a quick mock comment here, before merging 😄 I'll do it tomorrow, too late/lazy for now

**Review by albertmink — APPROVED** [review]
Look's good to me.

**Comment by albertmink** [comment]
Alright, but be aware of nightmares with regard to FUGR :smirk:

**Comment by larshp** [comment]
FUGR would look something like this, again, links broken, and quick guesses, so I doubt its correct,

# FUGR File Format

File | Cardinality | Definition | Schema | Example
:--- | :---  | :--- | :--- | :---
`<name>.fugr.json` | 1 | def | [`fugr.json`](../) | [`z_example.fugr.json`](./examples/z_aff_example_fugr.fugr.json)
`<name>.fugr.sapl<name>.reps.abap` | 1 | - | ABAP | [`z_example.fugr.saplz_example.reps.abap`](./examples/z_aff_example_fugr.fugr.saplz_aff_example_fugr.reps.abap) 
`<name>.fugr.sapl<name>.reps.json` | 1 | def | [`reps.json`](../) | [`z_example.fugr.saplz_example.reps.json`](./examples/z_aff_example_fugr.fugr.saplz_aff_example_fugr.reps.json)        
`<name>.fugr.l<name>top.reps.abap` | 1 | - | ABAP | [`z_example.fugr.lz_exampletop.reps.abap`](./examples/z_aff_example_fugr.fugr.lz_aff_example_fugrtop.reps.abap) 
`<name>.fugr.l<name>top.reps.json` | 1 | def | [`reps.json`](../) | [`z_example.fugr.lz_exampletop.reps.json`](./examples/z_aff_example_fugr.fugr.lz_exampletop.reps.json)         
`<name>.fugr.<fmname>.func.abap` | 0...n | - | ABAP | [`z_example.fugr.z_foobar.func.abap`](./examples/z_aff_example_fugr.fugr.z_aff_example_func.func.abap)                 
`<name>.fugr.<fmname>.func.json` | 0...n | def | [`func.json`](../) | [`z_example.fugr.z_foobar.func.json`](./examples/z_aff_example_fugr.fugr.z_aff_example_func.func.json)                 
`<name>.fugr.texts.<lang>.properties` | 0...n | ? | ? | [`z_example.fugr.texts.en.properties`](./examples/z_example.fugr.texts.en.properties)

**Comment by albertmink** [comment]
Actually this version is quite clear and 'easy' to read.

Cardinality of 0...n means that there might be an arbitrary number of that kind of file, right?
For classes the eclipse tab `Local Types` might be empty and hence not written. Does it have cardinality 0...1?

**Comment by larshp** [comment]
yeap

local types: yeap, "0...1"

possible cardinalities:
- 1
- 0...n
- 1...n
- 0...1

I don't think there will be anything with "2" files

**Comment by albertmink** [comment]
Great, this cardinality is helpful.

Is there a way to extract this discussion to an issue and track the adoption of the objects therein?

**Comment by larshp** [comment]
we can open an issue if this change is approved, would like a few more people to have a look first, this is quite central

**Comment by albertmink** [comment]
Moved discussion to issue #184

**Review by albertmink — APPROVED** [review]
Look's good to me.

**Pull request merged**
