### PR TITLE
Add documentation to type specification

### LINKED ISSUE #128: Interface file definitions naming
we currently have:

```
zif_oo_aff_intf_v1.intf.abap
zif_atc_aff_chkc_v1.intf.abap
```

`INTF` and `CHKC` are the TADIR R3TR names, which are guaranteed to be unique, I suggest leaving out the "_oo" and "_atc" parts

### PR DESCRIPTION
**Pull request by schneidermic0**
closes #128

### CODE REVIEW

**Comment by larshp** [comment]
if there is a definition for REPS(LIMU type), which folder will it be in?

**Comment by schneidermic0** [comment]
Currently REPS is located in the FUGR folder, because no other type in the repository uses it (yet).
If we reuse it, I suggest to create a REPS folder.

**Comment by larshp** [comment]
we already know REPS is part of PROG

but anyhow, this is where I find things to get difficult, when does things get folders? if looking for something where is it located? if there is both LIMU and R3TR folders, how do I determine which are which?

**Comment by schneidermic0** [comment]
@larshp Before I comment on this, one short question: How would you expect the `.abap` filename for a program R3TR PROG would look like?

**Comment by larshp** [comment]
my suggestion would be `zreport.prog.abap`, and then put all the metadata(REPT + CUAD + DOCU + DYNP + more?) into a single `zreport.prog.json` file, alternatively it could have 6+ files,

```abap
zfoobar.prog.zfoobar.rept.json
zfoobar.prog.zfoobar.cuad.json
zfoobar.prog.rezfoobar.docu.json
zfoobar.prog.2000.dynp.json
zfoobar.prog.json
zfoobar.prog.abap
```

which is the direction the current FUGR suggestion is moving in

related = https://github.com/SAP/abap-file-formats/issues/115

**Comment by schneidermic0** [comment]
The current suggestion for FUGR is the multiple-file approach (your 6+ files approach)

I think there is following difference between FUGR and PROG: Each include for a PROG is self-contained object which is stored in TADIR and can only be transported by specifying the include name. For FUGRs, you can transport all includes belonging to the function group (due to naming convention L<function group name>???; ? = placeholder for a single character) by transport R3TR FUGR. This means the includes in a FUGR a sub objects belonging to the FUGR. 
Other includes are standalone includes and might be included in a program, but they do not belong to the program. 
This also means includes of a program can be distributed over multiple packages. Includes of function groups can't be distributed in various packages.

Therefore, I think we don't need any REPS relation in programs in the file formats. Here the object type PROG is sufficient. And REPS becomes only a reusable part for function groups, module pools and so on.

**Review by wurzka — APPROVED** [review]
Looks good to me :)

**Comment by schneidermic0** [comment]
@larshp The discussion above does not hinder us to merge this PR, does it?

**Comment by larshp** [comment]
nah, just merge it

**Pull request merged**
