### PR TITLE
File Format for DDLX (CDS Metadata Extensions)

### PR DESCRIPTION
**Pull request by BeckerWdf**

### CODE REVIEW

**Comment by BeckerWdf** [comment]
@albertmink: Can you tell me what's fron with the README.md file?
As far as I see it has only LF line endings and a new line at the end of the file.

**Comment by larshp** [comment]
ref #161

**Comment by larshp** [comment]
for what its worth, I suggest prioritizing finishing DDLS before adding DDLX

**Comment by BeckerWdf** [comment]
> for what its worth, I suggest prioritizing finishing DDLS before adding DDLX

We will handle the improvements of DDLS later.

**Comment by albertmink** [comment]
@BeckerWdf, I agree. The file should be ok.

**Comment by BeckerWdf** [comment]
> @BeckerWdf, I agree. The file should be ok.

Can you please approve this PR?

**Review by albertmink — APPROVED** [review]
Look's good to me.

**Comment by BeckerWdf** [comment]
> ref #161

Fix my last commit this should be fixed

**Review by schneidermic0 — APPROVED** [review]
Looks good to me.

**Comment by BeckerWdf** [comment]
@larshp: Does this look good for you?

**Comment by larshp** [comment]
filename extension = `acds` is good

I have not looked through the details of the file format, should start fixing issues from the top of the list https://github.com/SAP/abap-file-formats/issues/148, DDLX is low on my list of priorities

**Pull request merged**
