### PR TITLE
add folder util for generic/reusable ABAP types

### LINKED ISSUE #175: Folder structure, suggest one folder per type
in https://github.com/SAP/abap-file-formats/tree/main/file-formats there are the `typesUsedForAll` and `typesUsedForClasAndIntf`, suggest moving the contents of these folders one level up and deleting the folders

This structure will allow for https://github.com/SAP/abap-file-formats/issues/169

### PR DESCRIPTION
**Pull request by albertmink**
closes #175

### CODE REVIEW

**Comment by larshp** [comment]
for moving up, I meant to https://github.com/SAP/abap-file-formats/tree/main/file-formats

so that every folder is for a object type, no special folders

**Comment by albertmink** [comment]
Ahhh, do you suggest to have folder `file-formats` with folders for objects `clas` .....  and some files `zif_aff.` ?

To have folders for object types and files for other things.

**Comment by larshp** [comment]
the thought was moving
`https://github.com/SAP/abap-file-formats/blob/main/file-formats/typesUsedForAll/zif_aff_types_v1.intf.abap`
to
`https://github.com/SAP/abap-file-formats/blob/main/file-formats/zif_aff_types_v1.intf.abap`
and
`https://github.com/SAP/abap-file-formats/blob/main/file-formats/typesUsedForClasAndIntf/zif_oo_aff_types_v1.intf.abap`
to
`https://github.com/SAP/abap-file-formats/blob/main/file-formats/zif_oo_aff_types_v1.intf.abap`

along with the 2 corresponding json files

not really sure how to get it working with the abaplint glob configuration, but it should be possible to fix somehow

**Comment by albertmink** [comment]
let's just move them as proposed above.

**Comment by larshp** [comment]
set the pattern to `/file-formats/*/{type,..}/*.intf.abap`, kind of a hack, but it seems to work 😁

**Comment by larshp** [comment]
alternatively, we can use `/file-formats/**/*.intf.abap` if `zif_aff_example.intf.abap` is fixed, and perhaps disable rule [method_parameter_names](https://rules.abaplint.org/method_parameter_names/)

**Comment by albertmink** [comment]
ok, I cannot control abapgit, @larshp can you take over?

**Review by wurzka — CHANGES_REQUESTED** [review]
In [specification.md](https://github.com/SAP/abap-file-formats/blob/doc/mv-generic-abap-types/doc/specification.md), the links to zif_aff_types_v1 have to be updated

**Review by wurzka — APPROVED** [review]
Thanks, LGTM :)

**Pull request merged**
