### PR TITLE
[DOMA] Add schema for domains

### LINKED ISSUE #285: Schema is missing for DOMA
SAP has to generate the schema file for domains

### PR DESCRIPTION
**Pull request by schneidermic0**
closes #285.

Additionally, I fixed some inconsistencies I (and our verification) missed in the review...

### CODE REVIEW

**Comment by schneidermic0** [comment]
#287 should fix the JSON validation. 

The markdown link checks reported `https://abapgit.org/`was broken. This does not seem to be the case. ;)

**Comment by larshp** [comment]
I've retriggered the links check, ok now

**Comment by schneidermic0** [comment]
#287 is not related to the issues reported in this PR. Anyhow it is good to have it, too. ;)

The JSON validation fails, because the schema was generated with `string` fields instead of `boolean`. Furthermore, the `originalLanguage` was set to upper case. I'll fix this later today.

**Review by albertmink — APPROVED** [review]
Look's good to me.

**Comment by albertmink** [comment]
Need to update the JSON Schema accordingly.

**Comment by schneidermic0** [comment]
What do you mean? Did I miss anything?

**Pull request merged**
