### PR TITLE
update scp1

### PR DESCRIPTION
**Pull request by huber-nicolas**

### CODE REVIEW

**Review by wurzka — APPROVED** [review]
LGTM :)

**Comment by huber-nicolas** [comment]
@schneidermic0 I just realised that this example is very big. It has 166 thousand rows. Do we need such a big example?

**Comment by schneidermic0** [comment]
> @schneidermic0 I just realised that this example is very big. It has 166 thousand rows. Do we need such a big example?

I guess this we have to discuss with the object type owners. I guess we can reduce it. ;)

However, this should not hinder you merge this PR. This can be also updated in a separate PR.

**Review by schneidermic0 — APPROVED** [review]
LGTM

**Pull request merged**
