### PR TITLE
[UIST] - Adjust field labels + make name of UIPG mandatory

### PR DESCRIPTION
**Pull request by DominikvonSchoenebeck**
Some field labels needed to be adjusted (1) to be compliant to official SAP speech and (2) to be consistent in all UI places.

### CODE REVIEW

**Comment by albertmink** [comment]
would you mind to generate the JSON Schema with the ABAP types in the PR? They seem to be out of sync.

**Comment by DominikvonSchoenebeck** [comment]
JSON schema got generated based on the ABAP interface type and both got inserted in the PR. Still the workflow review fails and I can't find the reason.
Is the order important? Commit first the interface type and then the JSON schema?

**Comment by albertmink** [comment]
Checks are all green, right?!

**Comment by DominikvonSchoenebeck** [comment]
Oh, I see. But why there is a red X next to my committed file?

**Review by albertmink — APPROVED** [review]
Looks good to me.

**Pull request merged**
