### PR TITLE
[UIAD] - Smooth out the structure of Custom tile and its properties

### PR DESCRIPTION
**Pull request by ViktoriaFreidel**
We reduce a substructure of custom tiles to be in sync with DB definition and for better Layout control
and side effects

### CODE REVIEW

**Comment by ViktoriaFreidel** [comment]
Could you help to understand and resolve compatibility check error? We change a sub structure, should we then use   "formatVersion": "2" ? Or there is on other reason of errors? Thank you.

**Comment by albertmink** [comment]
The Compatability Check helps to detect incompatible changes. It is however not 'required' and doesn't block merging.

Did you shipped the editor? If not, you might just ignore this check.

**Comment by ViktoriaFreidel** [comment]
Currently we are in development phase and shipment of the editor not done yet. 
I would to ask you for review.

**Review by albertmink — APPROVED** [review]
Thanks for the update. LGTM

**Pull request merged**
