### PR TITLE
Add timestamp to JSON Schema

### PR DESCRIPTION
**Pull request by albertmink**

### CODE REVIEW

**Comment by larshp** [comment]
dont think this will work out, it will cause changes to always happen in all files after regeneration, which I assume will always happen on all files

**Comment by larshp** [comment]
For future contributions, when the schema generation runs on github actions:
1: anyone opens a pull request with changes to ABAP objects
2: regeneration of all schemas happens automatically(there might be changes to the generation code)
3: if there are any changes in the schemas they are added to the pull request

with the timestamp, there will always be changes, so 3 will always happen

with git, git tracks the changes. Anyone needing the latest schemas can setup orchestration to get it from main, this orchestration will also break(or not work very well) if all schemas are always updated

**Comment by albertmink** [comment]
Yep, we need to observe carefully where this time stamp will bring us.

I am certainly not very optimistic towards the extra value of having a time step. It is a file in git, so no need to put a date inside anyhow?!

**Comment by albertmink** [comment]
No timestamp, for now, in the ABAP file formats specification. Once the JSON Schema writer is open sourced, people can adopt it to their preferences.

**Pull request closed without merging**
