### PR TITLE
[NONT]: Delete expanded name and update root node title

### PR DESCRIPTION
**Pull request by Ehret-Thomas**
* The expanded name has become obsolete for object type NONT is therefore deleted from the AFF interface.
* The title for the field `root_node_flag` is changed from "Root Node Flag" to "Root Node" in response to feedback from a UX review. 

This second improvement is visible in the form-based editor for object type NONT in ABAP Development Tools. 
Renaming also the field `root_node_flag` in the NONT AFF-interface is planned, but will probably be realized in the second AFF version accompanied by appropriate compatibility handling.

### CODE REVIEW

**Review by albertmink — APPROVED** [review]
LGTM

**Review by schneidermic0 — APPROVED** [review]
Thanks, @Ehret-Thomas

**Comment by schneidermic0** [comment]
> This second improvement is visible in the form-based editor for object type NONT in ABAP Development Tools.
Renaming also the field root_node_flag in the NONT AFF-interface is planned, but will probably be realized in the second AFF version accompanied by appropriate compatibility handling.

I think we can still change this object type incompatible as it is not used in repositories (such as abapGit), yet.

**Comment by huber-nicolas** [comment]
I talked to @Ehret-Thomas . He will open a new pull request as soon as he decided to rename the field root_node_flag in the NONT AFF-interface.

I will merge this pull request

**Pull request merged**
