### PR TITLE
remove old hand-written version of NROB and ENHO

### PR DESCRIPTION
**Pull request by albertmink**

### CODE REVIEW

**Review by huber-nicolas — APPROVED** [review]
For me it is ok to remove these two hand-written objects. In the next two-weeks I will upload the automatic generated NROB files.

**Comment by albertmink** [comment]
@SAP/abap-file-formats-admin please `squash and merge` the PR. 
All required actions are green, except the one that reports the EDITORCONFIG check results. The EDITORCONFIG checks themselves are green. Restarting the actions does not solve this one.

**Comment by larshp** [comment]
I guess its due to configuration? `VALIDATE_ALL_CODEBASE: false`, so it does not find any files, ie. no status is reported

It should be okay to validate everything every time? I think it will always take a magnitude longer time to download the super-linter docker image, than any actual linting, its just basics for this repo.

https://github.com/SAP/abap-file-formats/blob/amink/rm-old-format/.github/workflows/linter.yml

**Comment by albertmink** [comment]
Agree, we can `VALIDATE_ALL_CODEBASE` and apply the slim-image provided by the linter https://github.com/github/super-linter/#slim-image

**Pull request merged**
