### PR TITLE
rm old super-linter action for editorconfig

### PR DESCRIPTION
**Pull request by albertmink**

### CODE REVIEW

**Review by larshp — APPROVED** [review]

**Comment by larshp** [comment]
guess this also needs changes to required checks

**Comment by albertmink** [comment]
My intuition is telling me the same. However, the configuration says, all actions are allowed 😕

**Comment by larshp** [comment]
allowed, yes

issues is these two where the required part must be removed in branch protection(repo settings)
image

**Comment by albertmink** [comment]
Ok, I got it down to one 
image

What happens if we remove the `required` from the other linter? Would GitHub allow to merge, if linting action fails?

**Pull request merged**
