### PR TITLE
be more precise with json schema

### PR DESCRIPTION
**Pull request by albertmink**
- enforce checkName
  - allow only one of {value, valueList, ValueRangeList}
  - check for complete sign, option, low and high in ValueRangeLists
  - parameters must contain name and type
  - dropped the logic for type and valueRangeList, valueList, ...

### CODE REVIEW

**Comment by larshp** [comment]
is this an autogenerated json schema?

**Comment by albertmink** [comment]
sadly not

**Comment by larshp** [comment]
as far as I understand, the scope is to someday overwrite all the hand written json schemas

**Comment by huber-nicolas** [comment]
> as far as I understand, the scope is to someday overwrite all the hand written json schemas

Yes. Within the next few weeks we will exchange all the schemas in this repo with generated schemas (generated by a "schema writer API" using only the abap type as input).

**Comment by albertmink** [comment]
project moved to generated JSON schema

**Pull request closed without merging**
