### PR TITLE
Fix titles and descriptions for DMON, RONT, NONT

### PR DESCRIPTION
**Pull request by schneidermic0**
Object types DMON, RONT and NONT did not specify a title or description for `ty_main`. For this reason the JSON schema has neither a title nor a description.

See #561

### CODE REVIEW

**Review by larshp — APPROVED** [review]
LGTM

**Comment by schneidermic0** [comment]
closes #561

**Comment by schneidermic0** [comment]
Thanks @larshp for your review. I am waiting for input by @Ehret-Thomas until the end of the day. Latest then, I will merge it. If more changes are required (because @Ehret-Thomas does not manage to look into it, today), we could also add them later.

**Comment by larshp** [comment]
no hurry

**Review by Ehret-Thomas — APPROVED** [review]
Thanks for correcting this! LGTM, too 👍

**Pull request merged**
