### PR TITLE
Update Docu

### PR DESCRIPTION
**Pull request by wurzka**
Mention the reusable interface
Naming Convention
New Annotations
Updated example

### CODE REVIEW

**Comment by larshp** [comment]
A: file naming, suggest adding information as to what a "object type" is, personally I assume its a R3TR object, see #115
B: "Extreme Values", is this feature needed? I expect the schema generation to be based on the ABAP types
C: "Length Specification", is this feature needed? I expect the schema generation to be based on the ABAP types
D: "Default", is this feature needed? I expect the schema generation to be based on the ABAP types

I suggest prioritizing getting the schema generation running/automated first, instead of adding more features

**Comment by wurzka** [comment]
See #144. There is talked about the need for the new annotation.

**Comment by larshp** [comment]
heh, okay, I don't follow any of the new format files, only INTF + CHKO

**Comment by schneidermic0** [comment]
Relates to #128, but won't closes it until the interface names have been adapted

**Review by schneidermic0 — APPROVED** [review]
Thanks, LGTM.

**Pull request merged**
