### PR TITLE
Removed maxLength and pattern for language field

### PR DESCRIPTION
**Pull request by Markus1812**
refers to #582 
Generators updated with Pull Request https://github.com/SAP/abap-file-formats-tools/pull/310

Documentation will be updated in separate Pull Request.

### CODE REVIEW

**Review by albertmink — APPROVED** [review]
LGTM

Probably the admins have to overrule the check.

**Comment by schneidermic0** [comment]
> Probably the admins have to overrule the check.

As soon as https://github.com/SAP/abap-file-formats-tools/pull/310 is merged, I expect the checks to be green. Therefore, let's merge https://github.com/SAP/abap-file-formats-tools/pull/310 and rerun the tests, first

**Comment by schneidermic0** [comment]
I think we have to ignore results of "Compatability Check / Is change compatible (pull_request)". To be honest, I don't understand why the check is complaining about the changes. Nothing has been added here. Do I miss anything?

**Review by schneidermic0 — APPROVED** [review]
Looks good to me. Thanks, @Markus1812 

Welcome as contributor also to this repository :)

**Comment by albertmink** [comment]
Publishing is done one push to main. PR is not considered

**Pull request merged**
