### PR TITLE
Rename GH action for JSON data validation

### PR DESCRIPTION
**Pull request by albertmink**

### CODE REVIEW

**Comment by schneidermic0** [comment]
@albertmink Do you know whether the checks struggle with the "old" JSON data validation? The new (renamed) validation was successful.

**Comment by larshp** [comment]
someone with access must change the required status checks in repository settings

**Comment by schneidermic0** [comment]
> Done

**Review by schneidermic0 — APPROVED** [review]

**Comment by schneidermic0** [comment]
I have just added the renamed check to the required status check again

**Pull request merged**
